### ISSUE TITLE
Falling block not displayed

### ISSUE THREAD

**Issue by clach04** [plumino/plumino2#1]
Falling block not displayed - it is displayed briefly for a fraction of a second if it is rotated, screen shot:

![image](https://user-images.githubusercontent.com/424032/64396478-989e2300-d012-11e9-9713-f70ae21df0dd.png)

This is on Windows 10 with both love-11.2.0-win64 and love-11.2-win32 from https://bitbucket.org/rude/love/downloads/ (linked to from https://love2d.org/).

I'm not clear if this is a game bug or love2d bug.

**Comment by clach04** [comment]
This is with headrevs:

    commit 8b734f62a1e0c2168c294d0fcbf745592d956479 (HEAD -> master, origin/master, origin/HEAD)

**Comment by snightshade** [comment]
This is because the block is above the playfield. Try using Arika Rotation System.

**Comment by snightshade** [comment]
why did i leave this open
