### ISSUE TITLE
enhancement request - support user defined themes

### ISSUE THREAD

**Issue by clach04** [plumino/plumino2#2]
From looking at menu/code/assets it looks like themes need a code modification. It would be cool if themes could be changed without coding changes.

There are a few prior art different theme/skin approachs

 * https://www.golfgl.de/lightblocks/themes.html
 * tetrinet - e.g. http://www.sonic.net/~raiden/tetrinet.htm

**Comment by snightshade** [comment]
This is an interesting request, could you please elaborate on what could be themeable?

**Comment by clach04** [comment]
@ry00001 sorry for the delay in responding.

The silly answer is *EVERYTHING* ;)

The main two are audio and gfx with sub-options for those:

  * gfx
      * blocks
          * shape
          * colors
      * background(s) - playfield and/or surround
  * audio
      * sound effects (rotation, movement, 1 line line clear, double, end game, etc.)
      * music

There are a few different options for each. Right now it looks like gfx are in https://github.com/plumino/plumino2/tree/master/assets/gfx/mino and the same image is used for all pieces, with different colors applied.

This is similar to how (I think) https://www.golfgl.de/lightblocks/themes.html work.

Another way to tackle this is the way JStris skinning is done and how Tetrinet themes/skins worked, which is a different image for each block. E.g. a single image is provided that is 9 blocks across, heights are 32 or 64 pixels, for example for JSTris skins:

  * https://imgur.com/G6WbXoD
  * https://puu.sh/CRGQ8/96deec9eb6.png

Both systems have a meta data file to specify the audio.

**Comment by snightshade** [comment]
hm, this is interesting, i could start working on this

**Comment by snightshade** [comment]
@clach04 i have started working on this
this issue will be closed when skins are fully implemented

**Comment by snightshade** [comment]
As of plumino^2 version 7.0, almost all of the game's assets are fully skinnable.
