### ISSUE TITLE
Crash instantly on Android because of shader's failure

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [plumino/plumino2#5]
![Screenshot_20241208-163050.jpg](https://github.com/user-attachments/assets/0476c9bc-8a37-47a7-bfe7-a01b19a0e016)

As the title said
I hope this project may get some work, sorry for waking up an "ancient" project.

**Comment by snightshade** [comment]
This project is **long** unsupported. Please play a better game.
